<?php
/**
 * DataSourceConnectionType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastReport Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\cloud\fastreport\model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DataSourceConnectionType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DataSourceConnectionType
{
    /**
     * Possible values of this enum
     */
    const JSON = 'JSON';
    const MSSQL = 'MSSQL';
    const CSV = 'CSV';
    const XML = 'XML';
    const MY_SQL = 'MySQL';
    const POSTGRES = 'Postgres';
    const ORACLE_DB = 'OracleDB';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::JSON,
            self::MSSQL,
            self::CSV,
            self::XML,
            self::MY_SQL,
            self::POSTGRES,
            self::ORACLE_DB,
        ];
    }
}


