<?php
/**
 * DefaultPermissionsVM
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastReport Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\cloud\fastreport\model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DefaultPermissionsVM Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DefaultPermissionsVM extends CloudBaseVM
{
    public const DISCRIMINATOR = 't';

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DefaultPermissionsVM';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'file_permissions' => '\OpenAPI\Client\cloud\fastreport\model\FilePermissionsCRUDVM',
        'data_source_permissions' => '\OpenAPI\Client\cloud\fastreport\model\DataSourcePermissionsCRUDVM',
        'group_permissions' => '\OpenAPI\Client\cloud\fastreport\model\GroupPermissionsCRUDVM',
        'task_permissions' => '\OpenAPI\Client\cloud\fastreport\model\TaskPermissionsCRUDVM',
        't' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'file_permissions' => null,
        'data_source_permissions' => null,
        'group_permissions' => null,
        'task_permissions' => null,
        't' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'file_permissions' => false,
        'data_source_permissions' => false,
        'group_permissions' => false,
        'task_permissions' => false,
        't' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes + parent::openAPITypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats + parent::openAPIFormats();
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables + parent::openAPINullables();
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'file_permissions' => 'filePermissions',
        'data_source_permissions' => 'dataSourcePermissions',
        'group_permissions' => 'groupPermissions',
        'task_permissions' => 'taskPermissions',
        't' => '$t'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'file_permissions' => 'setFilePermissions',
        'data_source_permissions' => 'setDataSourcePermissions',
        'group_permissions' => 'setGroupPermissions',
        'task_permissions' => 'setTaskPermissions',
        't' => 'setT'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'file_permissions' => 'getFilePermissions',
        'data_source_permissions' => 'getDataSourcePermissions',
        'group_permissions' => 'getGroupPermissions',
        'task_permissions' => 'getTaskPermissions',
        't' => 'getT'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }



    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->setIfExists('file_permissions', $data ?? [], null);
        $this->setIfExists('data_source_permissions', $data ?? [], null);
        $this->setIfExists('group_permissions', $data ?? [], null);
        $this->setIfExists('task_permissions', $data ?? [], null);
        $this->setIfExists('t', $data ?? [], null);

        // Initialize discriminator property with the model name.
        $this->container['t'] = static::$openAPIModelName;
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['t'] === null) {
            $invalidProperties[] = "'t' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets file_permissions
     *
     * @return \OpenAPI\Client\cloud\fastreport\model\FilePermissionsCRUDVM|null
     */
    public function getFilePermissions()
    {
        return $this->container['file_permissions'];
    }

    /**
     * Sets file_permissions
     *
     * @param \OpenAPI\Client\cloud\fastreport\model\FilePermissionsCRUDVM|null $file_permissions file_permissions
     *
     * @return self
     */
    public function setFilePermissions($file_permissions)
    {
        if (is_null($file_permissions)) {
            throw new \InvalidArgumentException('non-nullable file_permissions cannot be null');
        }
        $this->container['file_permissions'] = $file_permissions;

        return $this;
    }

    /**
     * Gets data_source_permissions
     *
     * @return \OpenAPI\Client\cloud\fastreport\model\DataSourcePermissionsCRUDVM|null
     */
    public function getDataSourcePermissions()
    {
        return $this->container['data_source_permissions'];
    }

    /**
     * Sets data_source_permissions
     *
     * @param \OpenAPI\Client\cloud\fastreport\model\DataSourcePermissionsCRUDVM|null $data_source_permissions data_source_permissions
     *
     * @return self
     */
    public function setDataSourcePermissions($data_source_permissions)
    {
        if (is_null($data_source_permissions)) {
            throw new \InvalidArgumentException('non-nullable data_source_permissions cannot be null');
        }
        $this->container['data_source_permissions'] = $data_source_permissions;

        return $this;
    }

    /**
     * Gets group_permissions
     *
     * @return \OpenAPI\Client\cloud\fastreport\model\GroupPermissionsCRUDVM|null
     */
    public function getGroupPermissions()
    {
        return $this->container['group_permissions'];
    }

    /**
     * Sets group_permissions
     *
     * @param \OpenAPI\Client\cloud\fastreport\model\GroupPermissionsCRUDVM|null $group_permissions group_permissions
     *
     * @return self
     */
    public function setGroupPermissions($group_permissions)
    {
        if (is_null($group_permissions)) {
            throw new \InvalidArgumentException('non-nullable group_permissions cannot be null');
        }
        $this->container['group_permissions'] = $group_permissions;

        return $this;
    }

    /**
     * Gets task_permissions
     *
     * @return \OpenAPI\Client\cloud\fastreport\model\TaskPermissionsCRUDVM|null
     */
    public function getTaskPermissions()
    {
        return $this->container['task_permissions'];
    }

    /**
     * Sets task_permissions
     *
     * @param \OpenAPI\Client\cloud\fastreport\model\TaskPermissionsCRUDVM|null $task_permissions task_permissions
     *
     * @return self
     */
    public function setTaskPermissions($task_permissions)
    {
        if (is_null($task_permissions)) {
            throw new \InvalidArgumentException('non-nullable task_permissions cannot be null');
        }
        $this->container['task_permissions'] = $task_permissions;

        return $this;
    }

    /**
     * Gets t
     *
     * @return string
     */
    public function getT()
    {
        return $this->container['t'];
    }

    /**
     * Sets t
     *
     * @param string $t t
     *
     * @return self
     */
    public function setT($t)
    {
        if (is_null($t)) {
            throw new \InvalidArgumentException('non-nullable t cannot be null');
        }
        $this->container['t'] = $t;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


