<?php
/**
 * RunTransformTaskBaseVM
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastReport Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\cloud\fastreport\model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RunTransformTaskBaseVM Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class RunTransformTaskBaseVM implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RunTransformTaskBaseVM';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'locale' => 'string',
        'input_file' => '\OpenAPI\Client\cloud\fastreport\model\RunInputFileVM',
        'output_file' => '\OpenAPI\Client\cloud\fastreport\model\OutputFileVM',
        'transports' => '\OpenAPI\Client\cloud\fastreport\model\RunTransportTaskBaseVM[]',
        'subscription_id' => 'string',
        'type' => '\OpenAPI\Client\cloud\fastreport\model\TaskType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'locale' => null,
        'input_file' => null,
        'output_file' => null,
        'transports' => null,
        'subscription_id' => null,
        'type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'locale' => 'locale',
        'input_file' => 'inputFile',
        'output_file' => 'outputFile',
        'transports' => 'transports',
        'subscription_id' => 'subscriptionId',
        'type' => 'type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'locale' => 'setLocale',
        'input_file' => 'setInputFile',
        'output_file' => 'setOutputFile',
        'transports' => 'setTransports',
        'subscription_id' => 'setSubscriptionId',
        'type' => 'setType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'locale' => 'getLocale',
        'input_file' => 'getInputFile',
        'output_file' => 'getOutputFile',
        'transports' => 'getTransports',
        'subscription_id' => 'getSubscriptionId',
        'type' => 'getType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['locale'] = $data['locale'] ?? null;
        $this->container['input_file'] = $data['input_file'] ?? null;
        $this->container['output_file'] = $data['output_file'] ?? null;
        $this->container['transports'] = $data['transports'] ?? null;
        $this->container['subscription_id'] = $data['subscription_id'] ?? null;
        $this->container['type'] = $data['type'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['locale']) && !preg_match("/^[a-zA-Z]{2,4}(-[a-zA-Z]{2,4}){0,2}$/", $this->container['locale'])) {
            $invalidProperties[] = "invalid value for 'locale', must be conform to the pattern /^[a-zA-Z]{2,4}(-[a-zA-Z]{2,4}){0,2}$/.";
        }

        if (!is_null($this->container['transports']) && (count($this->container['transports']) > 10)) {
            $invalidProperties[] = "invalid value for 'transports', number of items must be less than or equal to 10.";
        }

        if (!is_null($this->container['subscription_id']) && !preg_match("/(^$)|(^[A-Fa-f0-9]{24}$)/", $this->container['subscription_id'])) {
            $invalidProperties[] = "invalid value for 'subscription_id', must be conform to the pattern /(^$)|(^[A-Fa-f0-9]{24}$)/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale locale
     *
     * @return self
     */
    public function setLocale($locale)
    {

        if (!is_null($locale) && (!preg_match("/^[a-zA-Z]{2,4}(-[a-zA-Z]{2,4}){0,2}$/", $locale))) {
            throw new \InvalidArgumentException("invalid value for $locale when calling RunTransformTaskBaseVM., must conform to the pattern /^[a-zA-Z]{2,4}(-[a-zA-Z]{2,4}){0,2}$/.");
        }

        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets input_file
     *
     * @return \OpenAPI\Client\cloud\fastreport\model\RunInputFileVM|null
     */
    public function getInputFile()
    {
        return $this->container['input_file'];
    }

    /**
     * Sets input_file
     *
     * @param \OpenAPI\Client\cloud\fastreport\model\RunInputFileVM|null $input_file input_file
     *
     * @return self
     */
    public function setInputFile($input_file)
    {
        $this->container['input_file'] = $input_file;

        return $this;
    }

    /**
     * Gets output_file
     *
     * @return \OpenAPI\Client\cloud\fastreport\model\OutputFileVM|null
     */
    public function getOutputFile()
    {
        return $this->container['output_file'];
    }

    /**
     * Sets output_file
     *
     * @param \OpenAPI\Client\cloud\fastreport\model\OutputFileVM|null $output_file output_file
     *
     * @return self
     */
    public function setOutputFile($output_file)
    {
        $this->container['output_file'] = $output_file;

        return $this;
    }

    /**
     * Gets transports
     *
     * @return \OpenAPI\Client\cloud\fastreport\model\RunTransportTaskBaseVM[]|null
     */
    public function getTransports()
    {
        return $this->container['transports'];
    }

    /**
     * Sets transports
     *
     * @param \OpenAPI\Client\cloud\fastreport\model\RunTransportTaskBaseVM[]|null $transports transports
     *
     * @return self
     */
    public function setTransports($transports)
    {

        if (!is_null($transports) && (count($transports) > 10)) {
            throw new \InvalidArgumentException('invalid value for $transports when calling RunTransformTaskBaseVM., number of items must be less than or equal to 10.');
        }
        $this->container['transports'] = $transports;

        return $this;
    }

    /**
     * Gets subscription_id
     *
     * @return string|null
     */
    public function getSubscriptionId()
    {
        return $this->container['subscription_id'];
    }

    /**
     * Sets subscription_id
     *
     * @param string|null $subscription_id subscription_id
     *
     * @return self
     */
    public function setSubscriptionId($subscription_id)
    {

        if (!is_null($subscription_id) && (!preg_match("/(^$)|(^[A-Fa-f0-9]{24}$)/", $subscription_id))) {
            throw new \InvalidArgumentException("invalid value for $subscription_id when calling RunTransformTaskBaseVM., must conform to the pattern /(^$)|(^[A-Fa-f0-9]{24}$)/.");
        }

        $this->container['subscription_id'] = $subscription_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \OpenAPI\Client\cloud\fastreport\model\TaskType|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \OpenAPI\Client\cloud\fastreport\model\TaskType|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


