<?php
/**
 * TimePeriodType
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastReport Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\cloud\fastreport\model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TimePeriodType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TimePeriodType
{
    /**
     * Possible values of this enum
     */
    const SECOND = 'Second';
    const MINUTE = 'Minute';
    const HOUR = 'Hour';
    const DAY = 'Day';
    const WEEK = 'Week';
    const MONTH = 'Month';
    const YEAR = 'Year';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SECOND,
            self::MINUTE,
            self::HOUR,
            self::DAY,
            self::WEEK,
            self::MONTH,
            self::YEAR,
        ];
    }
}


