<?php
/**
 * DownloadApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FastReport Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DownloadApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DownloadApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for downloadGetExport
     *
     * Returns a export file with specified id.
     *
     */
    public function testDownloadGetExport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadGetExportThumbnail
     *
     * Returns export's thumbnail.
     *
     */
    public function testDownloadGetExportThumbnail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadGetExports
     *
     * Returns a zip archive with selected ids.
     *
     */
    public function testDownloadGetExports()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadGetLastSVGExport
     *
     * returns export, that was created from report with specified id.  INTERNAL USAGE ONLY!.
     *
     */
    public function testDownloadGetLastSVGExport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadGetReport
     *
     * Returns a prepared file with specified id.
     *
     */
    public function testDownloadGetReport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadGetReportThumbnail
     *
     * Returns report's thumbnail.
     *
     */
    public function testDownloadGetReportThumbnail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadGetReports
     *
     * Returns a zip archive with selected files.
     *
     */
    public function testDownloadGetReports()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadGetTemplate
     *
     * Returns a Template file with specified id.
     *
     */
    public function testDownloadGetTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadGetTemplateThumbnail
     *
     * Returns template's thumbnail.
     *
     */
    public function testDownloadGetTemplateThumbnail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadGetTemplates
     *
     * Returns a zip archive with selected files.
     *
     */
    public function testDownloadGetTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
